### ISSUE TITLE
Topic kiezen voor backend en Frontend waarop je wilt focussen.

### ISSUE THREAD

**Issue by judithkoelewijn** [marcdroger/blok-tech-team#14]
https://github.com/cmda-bt/be-course-21-22/blob/main/topics.md

**Comment by judithkoelewijn** [comment]
Mijn idee voor topic: proper error handling (stukje onderzoek over error handling), en het uploaden van een afbeelding via Multer naar Mongodb (https://www.bezkoder.com/node-js-upload-store-images-mongodb/)

**Comment by AllyssaA** [comment]
Mijn topic idee: Use Mongoose to object model your database. Een abstracte laag toevoegen bovenop MongoDB door het gebruik van mongoose. Mongoose is een npm package voor nodejs applicaties. Mongoose maakt het mogelijk om schema's te definiëren, op deze manier krijgen we structuur.

https://stackabuse.com/mongoose-with-nodejs-object-data-modeling/

**Comment by marcdroger** [comment]
Ik kan wel aan de slag gaan met sessions in express.

**Comment by marcdroger** [comment]
@Neinno Gaat aan de slag met nodemailer.

**Comment by marcdroger** [comment]
@Neinno @AllyssaA @judithkoelewijn

Er moet ook nog een onderzoeks gedeelte in de wiki voor frontend over hoe je de applicatie production ready gaat maken. Denk hierbij aan een bundler, plaatjes compressen, sass gebruiken, en enz.

Hier wat voorbeelden van packages:
[https://www.npmjs.com/package/imageoptim-cli](https://www.npmjs.com/package/imageoptim-cli)
[https://www.npmjs.com/package/mozjpeg](https://www.npmjs.com/package/mozjpeg)

**Comment by marcdroger** [comment]
@marcdroger Ik ga aan de slag met het uitzoeken van verschillende taskrunners/module bundlers als research topic voor Frontend.

**Comment by marcdroger** [comment]
@Neinno Reminder. Alleen jij en ik hoeven een frontend topic te onderzoeken aangezien Judith en Allyssa dat vorig jaar gehaald hebben en dat nu niet hoeven te doen.

**Comment by marcdroger** [comment]
Dit is ook wel misschien iets wat we kunnen implementeren.

[https://www.digitalocean.com/community/tutorials/nodejs-compression](https://www.digitalocean.com/community/tutorials/nodejs-compression)
