### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by marcdroger** [marcdroger/blok-tech-team#16]
Navigatiebalk moet nagemaakt worden zoals in de wireframe.

[https://github.com/marcdroger/blok-tech-team/wiki/%E2%9C%8F%EF%B8%8F-Design](https://github.com/marcdroger/blok-tech-team/wiki/%E2%9C%8F%EF%B8%8F-Design)

**Comment by judithkoelewijn** [comment]
Navbar uitgewerkt, pull request gemaakt: https://github.com/marcdroger/blok-tech-team/pull/25
