### ISSUE TITLE
readme aanvullen

### ISSUE THREAD

**Issue by AllyssaA** [marcdroger/blok-tech-team#27]
Documenteren over:
- naam veranderen naar Edubroad
- het project/concept
- installatie
- features lijst (inloggen, registeren, account updaten bijv.)
- resources/acknowledgements

**Comment by marcdroger** [comment]
@AllyssaA Ik zie dat je deze al af hebt? Vergeet niet de main weer te mergen voordat je een Pull request gaat aanmaken.

**Comment by marcdroger** [comment]
@judithkoelewijn vergeet niet de main binnen te halen en te mergen.
Voeg bij bronnen nog de andere services toe. (gulp, postcss, autoprefix, cssnano)

[https://www.npmjs.com/package/autoprefixer](https://www.npmjs.com/package/autoprefixer)
gulp website
https://cssnano.co/
postcss github of npm package.
