### ISSUE TITLE
Logo/banner ontwerpen

### ISSUE THREAD

**Issue by marcdroger** [marcdroger/blok-tech-team#3]
Logo ontwerpen & banner voor het project.

Banner: 1200x630, png.

Svg formaat exporteren voor website & png voor favicon

Overhandig logo aan @marcdroger

**Comment by judithkoelewijn** [comment]
@marcdroger Ik heb het logo en de banner ontworpen en geëxporteerd. Je kan ze downloaden via WeTransfer: https://we.tl/t-t5cPZxP2Mr

Laat maar weten of je nog een afmeting of formaat mist, dan fix ik dat nog even.

**Comment by marcdroger** [comment]
Logo en banner in project toegevoegd. Word later samengevoegd in de main branch als de pull request is goedgekeurd.
