### ISSUE TITLE
Implementeer validator express

### ISSUE THREAD

**Issue by marcdroger** [marcdroger/blok-tech-team#35]
Onderzoek en voeg validatie toe in de backend voor de ingevulde data van de student.

Onderzoek plaatsen in de wiki.

[https://express-validator.github.io/docs/](https://express-validator.github.io/docs/)

**Comment by judithkoelewijn** [comment]
Documentatie: vanavond begonnen aan onderzoek en beschrijven documentatie in wiki. 
Nieuwe pagina aangemaakt op wiki met research en code voorbeelden: https://github.com/marcdroger/blok-tech-team/wiki/🧑🏽%E2%80%8D💻-Express-Validator

**Comment by marcdroger** [comment]
@judithkoelewijn goed stukje research gedaan! Laten we later nog kijken hoe we het beste alle research kunnen samenvoegen in de wiki.

**Comment by judithkoelewijn** [comment]
Thanks! Top, lijkt me helemaal goed :)

**Comment by marcdroger** [comment]
@judithkoelewijn De express validator code moet dus in een van de model js files komen te staan. In dit geval dan bij de update student. Maar aangezien op dit moment we niet de huidige status weten van die issue bekijken we dat later nog.

**Comment by judithkoelewijn** [comment]
<img width="1440" alt="Screenshot 2022-06-20 at 15 46 30" src="https://user-images.githubusercontent.com/74096730/174618291-dcf0e44d-2567-4034-a5e2-3b263338627b.png">

Validator implementatie is gelukt: bij niet geldig email adres komt er nu een foutmelding in JSON. Bij wel geldig adres wordt gebruiker aangemaakt, en stuurt Nodemailer bevestiging. Ik ga nu verder met het doorvoeren van een juiste manier van feedback sturen hierop (naar de gebruiker)

**Comment by marcdroger** [comment]
@judithkoelewijn Netjes. Het beste zou nu inderdaad zijn een p element met daarin de error message.

De css moet dan als volgt zijn:

Position fixed, top positie en center aligned. Het liefst een background kleur die opvalt met wat padding om de tekst heen.
De error bericht moet wegteklikken zijn of moet na 3/4 seconden automatisch verdwijnen.

Nog niet zeker welke manier het beste is. Dat vind jij vast wel uit.
