### ISSUE TITLE
Research samenvatten in wiki

### ISSUE THREAD

**Issue by marcdroger** [marcdroger/blok-tech-team#64]
Nodemailer & express validator samenvoegen in de wiki. Oude pages verwijderen.

**Comment by judithkoelewijn** [comment]
@Neinno  
Een bestand met research frontend, en een bestand met research backend

**Comment by Neinno** [comment]
Backend & Frontend topics staan nu bij elkaar. 

- https://github.com/marcdroger/blok-tech-team/wiki/%F0%9F%A7%91%F0%9F%8F%BD%E2%80%8D%F0%9F%92%BB-Frontend-Topics
- https://github.com/marcdroger/blok-tech-team/wiki/%F0%9F%94%ACBackend-Topics

**Comment by judithkoelewijn** [comment]
Top, ik sluit de issue bij deze.
