### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by marcdroger** [marcdroger/blok-tech-team#66]
Als het project af is moet er gecheckt worden of de applicatie in alle browsers goed werkt en er uit ziet. Vooral of het er goed uit ziet aangezien sommige browsers hun eigen standaarden forceren.

De website moet via lokaal of heroku gecheckt worden in:
- Firefox
- Opera
- Safari (alleen te testen voor MacOs gebruikers)
- Edge

Bekijk de pages, voer gegevens, en enz. Eventuele issue's kunnen binnen een branch van deze issue gefixed worden.

**Comment by marcdroger** [comment]
In MS Edge ziet er alles prima uit.

**Comment by judithkoelewijn** [comment]
![Screenshot 2022-06-22 at 15 40 57](https://user-images.githubusercontent.com/74096730/175044106-cd21b099-3b3f-4bc2-889e-b3c8037b4c93.png)
Safari gooit een eigen styling over de select dropdown (maar los van uiterlijk werkt de functionaliteit wel gewoon)

**Comment by judithkoelewijn** [comment]
@marcdroger Denk dat beide select issues niet persen erg zijn (en OS default overschreven worden). Bij Safari werken alle functionaliteiten verder naar behoren

**Comment by marcdroger** [comment]
In firefox word de select ook overschreven met eigen styling

![image](https://user-images.githubusercontent.com/11356517/175044806-e8db5ebe-43bc-4772-8050-f92b5ac94146.png)

**Comment by marcdroger** [comment]
@judithkoelewijn Top. Dan was dit even de snelle check. Ik ga deze issue dan sluiten en kijken of ik bij de refactor misschien hier nog naar kijk.
