### ISSUE TITLE
Validator data doorsturen naar client side (error fixen)

### ISSUE THREAD

**Issue by judithkoelewijn** [marcdroger/blok-tech-team#72]

**Comment by judithkoelewijn** [comment]
Nice :) Met @Neinno  en @AllyssaA  even door de code gegaan en probleem gefixt. Er zat een dubbele redirect in wat een error gaf, maar bij deze opgelost. Ik ga nu verder met het inladen van de data client-side in pug

**Comment by judithkoelewijn** [comment]
Werkt nu als volgt: als de validator errors heeft !erros.array = empty dan wordt de pagina geredirect naar het formulier (en wordt de error als object meegestuurd. If else (als het wél goed gaat) komt de gebruiker op de / route. Dit kan later nog aangepast worden naar nieuwe route

**Comment by marcdroger** [comment]
@judithkoelewijn Netjes, wat is de huidige status van deze issue? Werkt alles op dit moment zoals je wou?
