### ISSUE TITLE
Update school werkt niet bij account page

### ISSUE THREAD

**Issue by marcdroger** [marcdroger/blok-tech-team#74]
De huidige school waar een student op zit word niet geupdate bij de account page in het project en de database als je de school veranderd.

Dit is best wel is een dingetje die snel gefixed moet worden door iemand.

De andere gegevens worden wel gewoon geupdate.

![fdm7vL4uMY](https://user-images.githubusercontent.com/11356517/174824373-f69eb0d8-11fc-4928-8149-abffa71d2e1f.gif)

**Comment by AllyssaA** [comment]
Uhh ja ik zie het probleem al, het probleem ligt in account.pug bij de form staat bij de input van School `name='school'` en dat moet `name='currentSchool'` worden

**Comment by marcdroger** [comment]
@AllyssaA Ah nice. Dan kan iemand een branch aanmaken in dit issue en dan fixen.
